# Generated by Django 2.2.3 on 2019-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_id', models.IntegerField()),
                ('pd_name', models.TextField()),
                ('pd_real_price', models.CharField(max_length=50)),
                ('pd_current_price', models.CharField(max_length=50)),
                ('pd_best_price', models.CharField(max_length=50)),
                ('pd_URL', models.TextField()),
            ],
        ),
    ]
